export const UI = {
  'signal.1': 'Somewhere on your hard drive, a song is dying.',
  'signal.2': 'It was good. You know it was good.',
  'signal.3': "Let's go get it.",
  'q1.title': 'WHAT DO YOU MAKE?',
  'q1.sub': 'Pick your main lane — you can add more later.',
  'q2.title': 'HOW LONG HAVE YOU BEEN AT IT?',
  'q2.sub': 'No wrong answers. This tunes your starting stats.',
  'q3.title': 'WHAT KILLS YOUR SONGS?',
  'q3.sub': 'Be honest — this is where the coaching starts.',
  'q4.title': 'HOW DO YOU LIKE TO BE PUSHED?',
  'q4.hype': 'Hype me up',
  'q4.hype.sub': 'celebration is fuel',
  'q4.real': 'Keep it real',
  'q4.real.sub': 'honest, warm, direct',
  'q4.drill': 'Drill sergeant (gentle)',
  'q4.drill.sub': 'structure, kindly enforced',
  'q4.facts': 'Just the facts',
  'q4.facts.sub': 'numbers, no pep talk',
  'q5.title': 'WHEN DOES MUSIC HAPPEN FOR YOU?',
  'q5.weeknights': 'Weeknights',
  'q5.weeknights.sub': 'after-work sessions',
  'q5.weekends': 'Weekend deep dives',
  'q5.weekends.sub': 'long hauls',
  'q5.stolen': 'Stolen moments',
  'q5.stolen.sub': '20 minutes here and there',
  'q5.chaos': 'Chaos, honestly',
  'q5.chaos.sub': "no pattern and that's fine",
  'rescue.ask':
    "Okay. That song that's been sitting there. The one you thought about when I asked what kills your songs. What's it called?",
  'rescue.stage': "Where's it stuck?",
  'shelve.confirm': "Shelving isn't quitting. It's curation.",
  'walkaway.ask': 'Better or just different?',
  'session.tiny': 'LOGGED — TINY BUT REAL',
  'board.empty': 'The board is hungry. Feed it one idea.',
  'board.allShelved': 'Clean slate. Suspiciously clean.',
  'mic.blocked': 'MIC BLOCKED — TEXT IT INSTEAD',
} as const;

export type UiKey = keyof typeof UI;
